In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
my_array = np.array(my_list); my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
type(my_array)

numpy.ndarray

In [4]:
my_array.shape

(10,)

In [5]:
arange_array = np.arange(10); arange_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.full((5, 4), 6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

# Slicing Arrays

In [10]:
np1 = np.arange(1, 10); np1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Return 2,3,4,5,6
np1[1:6]

array([2, 3, 4, 5, 6])

In [12]:
# Return 7,8 with negative slice
np1[-3:-1]

array([7, 8])

In [13]:
# 2-6 in steps 2
np1[1:6:2]

array([2, 4, 6])

## 2D Arrays

In [14]:
np.random.seed(10)
random_array = np.random.randint(0, 40, size=(5, 5)); random_array

array([[ 9, 36, 15,  0, 28],
       [25, 29, 29,  8,  9],
       [ 0, 36, 16, 36, 11],
       [24, 33,  8, 36, 14],
       [13,  5, 13, 25, 13]])

In [15]:
random_array[2:, 1:4]

array([[36, 16, 36],
       [33,  8, 36],
       [ 5, 13, 25]])

In [16]:
np2 = np.arange(20)
print(np2.max())

19


# Copy vs View

In [17]:
np1 = np.arange(10)
np2 = np1.view() # Create a view
np3 = np1.copy() # Create a copy
print(f"Original NP1:      {np1}")
print(f"Original View NP2: {np2}")
print(f"Original Copy NP3: {np3}")

Original NP1:      [0 1 2 3 4 5 6 7 8 9]
Original View NP2: [0 1 2 3 4 5 6 7 8 9]
Original Copy NP3: [0 1 2 3 4 5 6 7 8 9]


In [18]:
# Change first item of Np1
np1[0] = 17
print(f"Changed NP1:       {np1}")
print(f"Original View NP2: {np2}")
print(f"Original Copy NP3: {np3}")

Changed NP1:       [17  1  2  3  4  5  6  7  8  9]
Original View NP2: [17  1  2  3  4  5  6  7  8  9]
Original Copy NP3: [0 1 2 3 4 5 6 7 8 9]


In [19]:
# Change first item of Copy
np3[0] = 99
print(f"Changed NP1:       {np1}")
print(f"Original View NP2: {np2}")
print(f"Changed Copy NP3:  {np3}")

Changed NP1:       [17  1  2  3  4  5  6  7  8  9]
Original View NP2: [17  1  2  3  4  5  6  7  8  9]
Changed Copy NP3:  [99  1  2  3  4  5  6  7  8  9]


In [20]:
# Change first item of view
np2[0] = 22
print(f"Changed NP1:       {np1}")
print(f"Changed View NP2:  {np2}")
print(f"Changed Copy NP3:  {np3}")

Changed NP1:       [22  1  2  3  4  5  6  7  8  9]
Changed View NP2:  [22  1  2  3  4  5  6  7  8  9]
Changed Copy NP3:  [99  1  2  3  4  5  6  7  8  9]


# Shape and Reshape Arrays

In [22]:
np1 = np.arange(15)
print(np1)
print(f"Shape: {np1.shape}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Shape: (15,)


In [38]:
np.random.seed(15)
np2 = np.random.randint(10,99, (4, 4))
print(np2)
print(f"Shape: {np2.shape}")

[[82 22 15 10]
 [38 37 81 85]
 [95 57 27 41]
 [33 42 72 20]]
Shape: (4, 4)


In [43]:
np2 = np2.reshape(2,-1)
print(np2)
print(f"Shape: {np2.shape}")

[[82 22 15 10 38 37 81 85]
 [95 57 27 41 33 42 72 20]]
Shape: (2, 8)


In [44]:
np2 = np2.reshape(2, 2, 4)
print(np2)
print(f"Shape: {np2.shape}")

[[[82 22 15 10]
  [38 37 81 85]]

 [[95 57 27 41]
  [33 42 72 20]]]
Shape: (2, 2, 4)


In [52]:
# Flatten to 1-D
np2 = np2.reshape(-1)
print(np2)
print(f"Shape: {np2.shape}")

[82 22 15 10 38 37 81 85 95 57 27 41 33 42 72 20]
Shape: (16,)


# Iterating Arrays

In [56]:
np1 = np.arange(10).reshape(2, 5)
"""for row in np1:
    for item in row:
        print(item)
"""
for item in np.nditer(np1):
    print(item)

0
1
2
3
4
5
6
7
8
9


# Sorting Arrays

In [60]:
np1 = np.arange(10, 0, -1)
sorted_np1 = np.sort(np1)
print(f"Np1:        {np1}")
print(f"Sorted Np1: {sorted_np1}")

Np1:        [10  9  8  7  6  5  4  3  2  1]
Sorted Np1: [ 1  2  3  4  5  6  7  8  9 10]


In [61]:
# Return a copy
print(f"Np1:        {np1}")
print(f"Sorted Np1: {sorted_np1}")
print(f"Np1:        {np1}")

Np1:        [10  9  8  7  6  5  4  3  2  1]
Sorted Np1: [ 1  2  3  4  5  6  7  8  9 10]
Np1:        [10  9  8  7  6  5  4  3  2  1]


In [79]:
np.random.seed(15)
np2 = np.random.randint(10, 99, (2, 2, 3))
sorted_np2 = np.sort(np2)
print(f"Original Np2\n\n {np2} \n")
print("Sorted Np2\n")
print(sorted_np2)

Original Np2

 [[[82 22 15]
  [10 38 37]]

 [[81 85 95]
  [57 27 41]]] 

Sorted Np2

[[[15 22 82]
  [10 37 38]]

 [[81 85 95]
  [27 41 57]]]
