In [3]:
import numpy as np

In [9]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
my_array = np.array(my_list); my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
type(my_array)

numpy.ndarray

In [11]:
my_array.shape

(10,)

In [12]:
arange_array = np.arange(10); arange_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.full((5, 4), 6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

# Slicing Arrays

In [23]:
np1 = np.arange(1, 10); np1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# Return 2,3,4,5,6
np1[1:6]

array([2, 3, 4, 5, 6])

In [36]:
# Return 7,8 with negative slice
np1[-3:-1]

array([7, 8])

In [37]:
# 2-6 in steps 2
np1[1:6:2]

array([2, 4, 6])

## 2D Arrays

In [42]:
np.random.seed(10)
random_array = np.random.randint(0, 40, size=(5, 5)); random_array

array([[ 9, 36, 15,  0, 28],
       [25, 29, 29,  8,  9],
       [ 0, 36, 16, 36, 11],
       [24, 33,  8, 36, 14],
       [13,  5, 13, 25, 13]])

In [49]:
random_array[2:, 1:4]

array([[36, 16, 36],
       [33,  8, 36],
       [ 5, 13, 25]])